PROJ_NAME = captagent
$(PROJ_NAME)_VER = 6.0.0
$(PROJ_NAME)_TAG = 6.0.0
$(PROJ_NAME)_PACKAGE_REVISION = $(shell cd $(SRC)/$(PROJ_NAME); ../config/revision-gen $($(PROJ_NAME)_TAG))
$(PROJ_NAME)_SRPM = $(PROJ_NAME)-$($(PROJ_NAME)_VER)-$($(PROJ_NAME)_PACKAGE_REVISION).src.rpm
$(PROJ_NAME)_TAR = $(PROJ_NAME)/$(PROJ_NAME)-$($(PROJ_NAME)_VER).tar.gz

$(PROJ_NAME)_SRPM_DEFS = \
	--define "BUILD_NUMBER $($(PROJ_NAME)_PACKAGE_REVISION)" \
	--define "VERSION_NUMBER $($(PROJ_NAME)_VER)"

$(PROJ_NAME)_RPM_DEFS = \
	--define="BUILD_NUMBER $($(PROJ_NAME)_PACKAGE_REVISION)" \
	--define "VERSION_NUMBER $($(PROJ_NAME)_VER)"
