AC_CONFIG_FILES([distr/el/kamailio.logrotate])
AC_CONFIG_FILES([distr/el/kamailio.service])
AC_CONFIG_FILES([distr/el/kamailio.spec])
AC_CONFIG_FILES([distr/el/kamailio.rsyslog])
AC_CONFIG_FILES([distr/el/kamailio.sysconfig])
