// @ts-nocheck
import { useCallback, useMemo, useState } from 'react'
import { displaySrcIp } from '@/lib/ipAliasDisplay'
import { Download, FileText, Network, Play, Check, Copy, Loader2, AlertCircle, ExternalLink } from 'lucide-react'
import { Alert, AlertDescription } from '@/components/ui/alert'
import { Button } from '@/components/ui/button'
import { ScrollArea } from '@/components/ui/scroll-area'
import { resolveTimeRange, type CalendarPreset } from './utils/resolveTimeRange'
import { useDashboard } from './context/DashboardContext'
import { getAuthToken } from '@/lib/authTokenStorage'
import MultiSelectInput from './components/MultiSelectInput'
import { useExportExclusionHosts } from './useExportExclusionHosts'

// ── Helpers ───────────────────────────────────────────────────────────────────

function getToken(): string {
  return getAuthToken()
}

function absoluteApiUrl(path: string): string {
  if (path.startsWith('http://') || path.startsWith('https://')) return path
  if (typeof window === 'undefined') return path
  return `${window.location.origin}${path}`
}

function pickStr(obj: Record<string, unknown> | null | undefined, ...keys: string[]): string {
  if (!obj) return ''
  for (const k of keys) {
    const v = obj[k]
    if (typeof v === 'string' && v.length > 0) return v
  }
  return ''
}

/** Resolve browser view URL from export/link response (snake_case or camelCase, or view_uuid only). */
function resolveBrowserViewUrl(data: Record<string, unknown> | null | undefined): string {
  if (!data) return ''
  const path = pickStr(data, 'url_view', 'urlView')
  if (path) return absoluteApiUrl(path)
  const vid = pickStr(data, 'view_uuid', 'viewUuid')
  if (vid) return absoluteApiUrl(`/export/view/${vid}`)
  return ''
}

async function downloadBlob(url: string, body: object, filename: string) {
  const token = getToken()
  const res = await fetch(url, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      ...(token ? { Authorization: `Bearer ${token}` } : {}),
    },
    body: JSON.stringify(body),
  })
  if (!res.ok) {
    const txt = await res.text().catch(() => `HTTP ${res.status}`)
    throw new Error(txt)
  }
  const blob = await res.blob()
  const objUrl = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = objUrl
  a.download = filename
  a.click()
  URL.revokeObjectURL(objUrl)
}

// ── Gossipper XML generator (client-side) ─────────────────────────────────────

function buildGossipperXML(sessionId: string, items: any[]): string {
  if (!items || items.length === 0) return ''

  const uacIp = items[0]?.src_ip || ''
  const uacAlias = displaySrcIp(items[0] || {})
  const uacHint =
    uacIp && uacAlias && uacAlias !== uacIp
      ? `  <!-- UAC: ${uacAlias} (IP ${uacIp}) -->\n`
      : uacIp
        ? `  <!-- UAC IP: ${uacIp} -->\n`
        : ''
  const steps: string[] = []

  for (const item of items) {
    const isLocal = item.src_ip === uacIp
    const method: string = item.method || ''
    const responseCode = item.response_code ? String(item.response_code) : ''
    const payload: string = item.payload || ''

    if (responseCode && responseCode !== '0') {
      const label = item.event || responseCode
      if (isLocal) {
        const body = payload
          ? `<![CDATA[\n${payload}\n]]>`
          : `<![CDATA[\nSIP/2.0 ${responseCode} ${label}\n[last_Via:]\n[last_From:]\n[last_To:];tag=[call_number]\n[last_Call-ID:]\n[last_CSeq:]\nContent-Length: 0\n\n]]>`
        steps.push(`  <send>\n    ${body}\n  </send>`)
      } else {
        const optional = responseCode === '100' || responseCode === '180' || responseCode === '183'
        steps.push(`  <recv response="${responseCode}"${optional ? ' optional="true"' : ''} />`)
      }
    } else if (method) {
      if (isLocal) {
        const body = payload
          ? `<![CDATA[\n${payload}\n]]>`
          : `<![CDATA[\n${method} sip:[service]@[remote_ip]:[remote_port] SIP/2.0\nVia: SIP/2.0/[transport] [local_ip]:[local_port];branch=[branch]\nFrom: <sip:${item.caller || 'user'}@[local_ip]>;tag=[call_number]\nTo: <sip:${item.callee || 'service'}@[remote_ip]>\nCall-ID: [call_id]\nCSeq: [cseq] ${method}\nContact: <sip:[local_ip]:[local_port]>\nContent-Length: 0\n\n]]>`
        steps.push(`  <send>\n    ${body}\n  </send>`)
      } else {
        steps.push(`  <recv request="${method}" />`)
      }
    }
  }

  const safeName = sessionId.replace(/[^a-zA-Z0-9_-]/g, '_').slice(0, 40)
  return `<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE scenario SYSTEM "sipp.dtd">
<!-- Generated by HOMER | Session: ${sessionId} -->
<scenario name="homer_${safeName}">
${uacHint}
${steps.join('\n\n')}

  <ResponseTimeRepartition value="10, 20, 30, 40, 50, 100, 150, 200"/>
  <CallLengthRepartition value="10, 50, 100, 500, 1000, 5000, 10000"/>
</scenario>
`
}

// ── Inline download card (Text / PCAP) ───────────────────────────────────────

interface DirectExportCardProps {
  title: string
  description: string
  icon: React.ReactNode
  endpoint: string
  filename: string
  getRequestBody: () => object
}

function DirectExportCard({
  title, description, icon, endpoint, filename, getRequestBody,
}: DirectExportCardProps) {
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState('')

  const doExport = async () => {
    setBusy(true)
    setError('')
    try {
      await downloadBlob(endpoint, getRequestBody(), filename)
    } catch (e) {
      setError(e.message || 'Export failed')
    } finally {
      setBusy(false)
    }
  }

  return (
    <div className="rounded-lg border border-border bg-card p-4 space-y-3">
      <div className="flex items-center gap-2">
        <span className="text-primary">{icon}</span>
        <div>
          <p className="text-sm font-medium">{title}</p>
          <p className="text-[11px] text-muted-foreground">{description}</p>
        </div>
      </div>

      {error && (
        <Alert variant="destructive" className="py-2">
          <AlertCircle className="size-3.5" />
          <AlertDescription className="text-xs">{error}</AlertDescription>
        </Alert>
      )}

      <Button size="sm" onClick={doExport} disabled={busy} className="h-7 text-xs">
        {busy
          ? <Loader2 className="mr-1.5 size-3.5 animate-spin" />
          : <Download className="mr-1.5 size-3.5" />}
        {busy ? 'Exporting…' : 'Download'}
      </Button>
    </div>
  )
}

// ── Gossipper export card ──────────────────────────────────────────────────────

interface GossipperCardProps {
  sessionId: string
  items: any[]
}

function GossipperCard({ sessionId, items }: GossipperCardProps) {
  const [xml, setXml] = useState('')
  const [copied, setCopied] = useState(false)

  const generate = () => setXml(buildGossipperXML(sessionId, items))

  const download = () => {
    const blob = new Blob([xml], { type: 'application/xml' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `gossipper_${sessionId.replace(/[^a-zA-Z0-9_-]/g, '_').slice(0, 40)}.xml`
    a.click()
    URL.revokeObjectURL(url)
  }

  const copy = async () => {
    try {
      await navigator.clipboard.writeText(xml)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    } catch { /* ignore */ }
  }

  return (
    <div className="rounded-lg border border-border bg-card p-4 space-y-3">
      <div className="flex items-center gap-2">
        <span className="text-primary"><Play className="size-4" /></span>
        <div>
          <p className="text-sm font-medium">Gossipper / SIPp Scenario</p>
          <p className="text-[11px] text-muted-foreground">
            Generate an XML scenario file for Gossipper or SIPp to replay this call
          </p>
        </div>
      </div>

      {!xml ? (
        <Button size="sm" onClick={generate} disabled={!items?.length} className="h-7 text-xs">
          <Play className="mr-1.5 size-3.5" />
          Generate Scenario
        </Button>
      ) : (
        <div className="space-y-2">
          <ScrollArea className="h-56 rounded border border-border bg-muted/30">
            <pre className="p-2 font-mono text-[10px] leading-relaxed whitespace-pre text-foreground">
              {xml}
            </pre>
          </ScrollArea>
          <div className="flex gap-2">
            <Button size="sm" onClick={download} className="h-7 text-xs">
              <Download className="mr-1.5 size-3.5" />
              Download .xml
            </Button>
            <Button size="sm" variant="outline" onClick={copy} className="h-7 text-xs">
              {copied ? <Check className="mr-1.5 size-3.5 text-green-500" /> : <Copy className="mr-1.5 size-3.5" />}
              {copied ? 'Copied!' : 'Copy'}
            </Button>
            <Button size="sm" variant="ghost" onClick={() => setXml('')} className="h-7 text-xs ml-auto">
              Reset
            </Button>
          </div>
        </div>
      )}
    </div>
  )
}

// ── Share link (public export by id, like classic Homer /export/call/transaction/link) ──

interface ShareExportCardProps {
  getRequestBody: () => object
}

function ShareExportCard({ getRequestBody }: ShareExportCardProps) {
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState('')
  const [uuid, setUuid] = useState('')
  const [urlView, setUrlView] = useState('')
  const [urlText, setUrlText] = useState('')
  const [urlPcap, setUrlPcap] = useState('')
  const [viewWarning, setViewWarning] = useState('')
  const [copied, setCopied] = useState<'view' | 'text' | 'pcap' | 'uuid' | null>(null)

  const createLink = async () => {
    setBusy(true)
    setError('')
    setViewWarning('')
    setUuid('')
    setUrlView('')
    setUrlText('')
    setUrlPcap('')
    try {
      const token = getToken()
      const res = await fetch('/api/v4/transactions/export/link', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          ...(token ? { Authorization: `Bearer ${token}` } : {}),
        },
        body: JSON.stringify(getRequestBody()),
      })
      if (!res.ok) {
        const txt = await res.text().catch(() => `HTTP ${res.status}`)
        throw new Error(txt)
      }
      const json = await res.json()
      const d = json?.data as Record<string, unknown> | undefined
      const metaMsg = typeof json?.meta?.message === 'string' ? json.meta.message : ''
      if (!pickStr(d, 'uuid')) throw new Error('No uuid in response')
      setUuid(pickStr(d, 'uuid'))
      setUrlView(resolveBrowserViewUrl(d))
      setUrlText(pickStr(d, 'url_text', 'urlText') ? absoluteApiUrl(pickStr(d, 'url_text', 'urlText')) : '')
      setUrlPcap(pickStr(d, 'url_pcap', 'urlPcap') ? absoluteApiUrl(pickStr(d, 'url_pcap', 'urlPcap')) : '')
      if (metaMsg.startsWith('browser_view_unavailable')) {
        setViewWarning('Browser view link was not created (server-side). Text/PCAP links still work. Restart homer-core or check settings DB / logs.')
      }
    } catch (e) {
      setError(e.message || 'Failed to create share link')
    } finally {
      setBusy(false)
    }
  }

  const openView = () => {
    if (urlView) window.open(urlView, '_blank', 'noopener,noreferrer')
  }

  const copy = async (kind: 'view' | 'text' | 'pcap' | 'uuid') => {
    const s = kind === 'view' ? urlView : kind === 'text' ? urlText : kind === 'pcap' ? urlPcap : uuid
    if (!s) return
    try {
      await navigator.clipboard.writeText(s)
      setCopied(kind)
      setTimeout(() => setCopied(null), 2000)
    } catch { /* ignore */ }
  }

  return (
    <div className="rounded-lg border border-border bg-card p-4 space-y-3">
      <div className="flex items-center gap-2">
        <span className="text-primary"><Copy className="size-4" /></span>
        <div>
          <p className="text-sm font-medium">Shared export link</p>
          <p className="text-[11px] text-muted-foreground">
            Time-limited links (72h): open the call in a browser (HTML view; limited opens per link, see server transaction_view_max_opens) or download Text/PCAP via GET without logging in.
          </p>
        </div>
      </div>
      {error && (
        <Alert variant="destructive" className="py-2">
          <AlertCircle className="size-3.5" />
          <AlertDescription className="text-xs">{error}</AlertDescription>
        </Alert>
      )}
      {viewWarning && !error && (
        <Alert variant="default" className="border-amber-500/50 bg-amber-500/10 py-2">
          <AlertCircle className="size-3.5 text-amber-600" />
          <AlertDescription className="text-xs text-amber-950 dark:text-amber-100">{viewWarning}</AlertDescription>
        </Alert>
      )}
      {!uuid ? (
        <Button size="sm" onClick={createLink} disabled={busy} className="h-7 text-xs">
          {busy ? <Loader2 className="mr-1.5 size-3.5 animate-spin" /> : <Copy className="mr-1.5 size-3.5" />}
          {busy ? 'Creating…' : 'Create share link'}
        </Button>
      ) : (
        <div className="space-y-2 text-[11px]">
          {urlView ? (
            <div>
              <span className="text-muted-foreground flex items-center gap-1">
                <ExternalLink className="size-3 shrink-0" />
                Browser view (GET, limited opens)
              </span>
              <div className="mt-0.5 flex flex-wrap items-center gap-2">
                <code className="min-w-0 flex-1 break-all rounded border border-border bg-muted/40 px-2 py-1 font-mono text-[10px]">{urlView}</code>
                <Button type="button" size="sm" variant="default" className="h-7 shrink-0 text-xs" onClick={openView}>
                  Open
                </Button>
                <Button type="button" size="sm" variant="outline" className="h-7 shrink-0 text-xs" onClick={() => copy('view')}>
                  {copied === 'view' ? <Check className="size-3.5" /> : <Copy className="size-3.5" />}
                </Button>
              </div>
            </div>
          ) : null}
          <div>
            <span className="text-muted-foreground">Export share UUID (GET text/pcap)</span>
            <div className="mt-0.5 flex items-center gap-2">
              <code className="flex-1 break-all rounded border border-border bg-muted/40 px-2 py-1 font-mono text-[10px]">{uuid}</code>
              <Button type="button" size="sm" variant="outline" className="h-7 shrink-0 text-xs" onClick={() => copy('uuid')}>
                {copied === 'uuid' ? <Check className="size-3.5" /> : <Copy className="size-3.5" />}
              </Button>
            </div>
          </div>
          <div>
            <span className="text-muted-foreground">Text export URL (GET)</span>
            <div className="mt-0.5 flex items-center gap-2">
              <code className="flex-1 break-all rounded border border-border bg-muted/40 px-2 py-1 font-mono text-[10px]">{urlText}</code>
              <Button type="button" size="sm" variant="outline" className="h-7 shrink-0 text-xs" onClick={() => copy('text')}>
                {copied === 'text' ? <Check className="size-3.5" /> : <Copy className="size-3.5" />}
              </Button>
            </div>
          </div>
          <div>
            <span className="text-muted-foreground">PCAP export URL (GET)</span>
            <div className="mt-0.5 flex items-center gap-2">
              <code className="flex-1 break-all rounded border border-border bg-muted/40 px-2 py-1 font-mono text-[10px]">{urlPcap}</code>
              <Button type="button" size="sm" variant="outline" className="h-7 shrink-0 text-xs" onClick={() => copy('pcap')}>
                {copied === 'pcap' ? <Check className="size-3.5" /> : <Copy className="size-3.5" />}
              </Button>
            </div>
          </div>
          <p className="text-muted-foreground">
            Text/PCAP:
            {' '}
            <code className="rounded bg-muted/50 px-1">curl -f -L -o export.txt &quot;&lt;url&gt;&quot;</code>
            {' '}
            or open the URL in a browser (no Authorization header).
          </p>
          <Button size="sm" variant="ghost" className="h-7 text-xs" onClick={() => { setUuid(''); setUrlView(''); setUrlText(''); setUrlPcap(''); setViewWarning('') }}>
            Create another link
          </Button>
        </div>
      )}
    </div>
  )
}

// ── Main ExportTab ────────────────────────────────────────────────────────────

interface ExportTabProps {
  sessionId: string
  /** When set (2+ Call-IDs), export APIs use aggregated session_ids. */
  sessionIds?: string[]
  items: any[]
  timeRange?: { from?: number; to?: number; activePreset?: number | null; calendarPreset?: CalendarPreset | null }
  protoType?: number
  eventType?: string
}

export default function ExportTab({
  sessionId,
  sessionIds,
  items,
  timeRange,
  protoType = 1,
  eventType = 'call',
}: ExportTabProps) {
  const { timeZone } = useDashboard()
  const ids = (sessionIds && sessionIds.length > 1) ? sessionIds : null
  const { options: exclusionOptions, selectedIPs, setSelectedIPs, loading: exclusionLoading } =
    useExportExclusionHosts(items)

  const multiSelectOptions = useMemo(
    () => exclusionOptions.map((o) => ({ value: o.ip, name: o.label })),
    [exclusionOptions],
  )

  const getRequestBody = useCallback(() => {
    const ts = resolveTimeRange(timeRange, timeZone)
    const body: Record<string, unknown> = {
      ...(ids ? { session_ids: ids } : { session_id: sessionId }),
      proto_type: protoType,
      event_type: eventType,
      ...(ts ? { timestamp: { from: ts.from, to: ts.to } } : {}),
    }
    if (selectedIPs.length > 0) {
      body.whitelist = selectedIPs
    }
    return body
  }, [ids, sessionId, protoType, eventType, timeRange, timeZone, selectedIPs])

  const safeSid = (ids ? `multi_${ids.length}_sessions` : sessionId).replace(/[^a-zA-Z0-9_-]/g, '_').slice(0, 64)

  return (
    <div className="h-full overflow-auto p-4 space-y-3">
      <div className="rounded-lg border border-border bg-card p-4 space-y-2">
        <div>
          <p className="text-sm font-medium">Export Exclusion</p>
          <p className="text-[11px] text-muted-foreground">
            Exclude selected IPs from PCAP and text export (internal infrastructure, SBCs, etc.).
            Defaults come from Advanced settings (export / transaction / excludedCIDR).
          </p>
        </div>
        <MultiSelectInput
          options={multiSelectOptions}
          value={selectedIPs}
          onChange={setSelectedIPs}
          placeholder={exclusionLoading ? 'Loading hosts…' : 'No IPs excluded'}
          className="max-w-xl"
        />
      </div>

      <DirectExportCard
        title="Text Export"
        description="Download all SIP messages as plain text — one message per block with headers"
        icon={<FileText className="size-4" />}
        endpoint="/api/v4/transactions/export/text"
        filename={`homer_${safeSid}.txt`}
        getRequestBody={getRequestBody}
      />

      <DirectExportCard
        title="PCAP Export"
        description="Download captured SIP packets as a PCAP file, openable in Wireshark"
        icon={<Network className="size-4" />}
        endpoint="/api/v4/transactions/export/pcap"
        filename={`homer_${safeSid}.pcap`}
        getRequestBody={getRequestBody}
      />

      <ShareExportCard getRequestBody={getRequestBody} />

      <GossipperCard sessionId={sessionId} items={items} />
    </div>
  )
}
