// Copyright (C) 2026 Homer Server Contributors
//
// SPDX-License-Identifier: AGPL-3.0-or-later

package config

import (
	"crypto/rand"
	"encoding/base64"
	"fmt"
	"net"
	"os"
	"path/filepath"
	"strings"
)

const homerNodeAuthTokenFileName = ".homer_node_auth_token"

// NodeAuthTokenFilePath returns the persisted node HTTP auth token path
// beside the DuckLake catalog file.
func NodeAuthTokenFilePath(catalogPath string) string {
	catalogPath = strings.TrimSpace(catalogPath)
	if catalogPath == "" {
		catalogPath = "/data/homer_catalog.sqlite"
	}
	return filepath.Join(filepath.Dir(catalogPath), homerNodeAuthTokenFileName)
}

// IsLoopbackBindHost reports whether host is a loopback-only listen address.
// Empty host is treated as non-loopback (Go Listen binds all interfaces).
func IsLoopbackBindHost(host string) bool {
	host = strings.TrimSpace(strings.ToLower(host))
	if host == "" || host == "0.0.0.0" || host == "::" || host == "[::]" {
		return false
	}
	if host == "localhost" || host == "127.0.0.1" || host == "::1" || host == "[::1]" {
		return true
	}
	ip := net.ParseIP(strings.Trim(host, "[]"))
	return ip != nil && ip.IsLoopback()
}

// ResolveNodeFlightAuthToken returns the effective Bearer token for the node
// HTTP API (/query, /vacuum) and Airport when configured.
//
// Non-empty configuredToken wins. When empty and host is loopback-only, the
// token stays empty (trusted all-in-one). When empty and host is exposed
// (default 0.0.0.0), loads .homer_node_auth_token beside catalogPath; if
// missing, generates a random token, persists it (0600), and returns
// autoGenerated=true.
func ResolveNodeFlightAuthToken(host, configuredToken, catalogPath string) (token string, autoGenerated bool, tokenFile string, err error) {
	if s := strings.TrimSpace(configuredToken); s != "" {
		return s, false, "", nil
	}
	if IsLoopbackBindHost(host) {
		return "", false, "", nil
	}

	tokenFile = NodeAuthTokenFilePath(catalogPath)
	data, readErr := os.ReadFile(tokenFile)
	if readErr == nil {
		if s := strings.TrimSpace(string(data)); s != "" {
			return s, false, tokenFile, nil
		}
	} else if !os.IsNotExist(readErr) {
		return "", false, tokenFile, fmt.Errorf("read node auth token file %s: %w", tokenFile, readErr)
	}

	b := make([]byte, 32)
	if _, err := rand.Read(b); err != nil {
		return "", false, tokenFile, fmt.Errorf("generate node auth token: %w", err)
	}
	token = base64.RawURLEncoding.EncodeToString(b)
	if err := os.MkdirAll(filepath.Dir(tokenFile), 0o750); err != nil {
		return "", false, tokenFile, fmt.Errorf("create node auth token directory: %w", err)
	}
	if err := os.WriteFile(tokenFile, []byte(token+"\n"), 0o600); err != nil {
		return "", false, tokenFile, fmt.Errorf("write node auth token file %s: %w", tokenFile, err)
	}
	return token, true, tokenFile, nil
}
