// Copyright (C) 2025 Homer Server Contributors
//
// SPDX-License-Identifier: AGPL-3.0-or-later

package services

import (
	"crypto/rand"
	"encoding/base64"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const homerJWTSecretFileName = ".homer_jwt_secret"

// JWTSecretFilePath returns the persisted JWT secret path beside settingsDBPath.
func JWTSecretFilePath(settingsDBPath string) string {
	settingsDBPath = strings.TrimSpace(settingsDBPath)
	if settingsDBPath == "" {
		settingsDBPath = "/var/lib/homer/homer_settings.duckdb"
	}
	return filepath.Join(filepath.Dir(settingsDBPath), homerJWTSecretFileName)
}

// ResolveCoordinatorJWTSecret returns the effective JWT signing secret.
// Configured non-empty coordinator.jwt.secret wins. When empty, loads
// .homer_jwt_secret beside settings_db_path; if missing, generates a random
// secret, persists it (0600), and returns autoGenerated=true.
func ResolveCoordinatorJWTSecret(configuredSecret, settingsDBPath string) (secret string, autoGenerated bool, secretFile string, err error) {
	if s := strings.TrimSpace(configuredSecret); s != "" {
		return s, false, "", nil
	}
	secretFile = JWTSecretFilePath(settingsDBPath)
	data, readErr := os.ReadFile(secretFile)
	if readErr == nil {
		if s := strings.TrimSpace(string(data)); s != "" {
			return s, false, secretFile, nil
		}
	} else if !os.IsNotExist(readErr) {
		return "", false, secretFile, fmt.Errorf("read jwt secret file %s: %w", secretFile, readErr)
	}

	b := make([]byte, 32)
	if _, err := rand.Read(b); err != nil {
		return "", false, secretFile, fmt.Errorf("generate jwt secret: %w", err)
	}
	secret = base64.RawURLEncoding.EncodeToString(b)
	if err := os.MkdirAll(filepath.Dir(secretFile), 0o750); err != nil {
		return "", false, secretFile, fmt.Errorf("create jwt secret directory: %w", err)
	}
	if err := os.WriteFile(secretFile, []byte(secret+"\n"), 0o600); err != nil {
		return "", false, secretFile, fmt.Errorf("write jwt secret file %s: %w", secretFile, err)
	}
	return secret, true, secretFile, nil
}
