#!/bin/sh
### BEGIN INIT INFO
# Provides: homer-core
# Required-Start:	$syslog $local_fs $remote_fs $network
# Required-Stop:	$syslog $local_fs $remote_fs $network
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description: HEPAgent
### END INIT INFO

. /lib/lsb/init-functions
prog=homer-core
PIDFILE=/var/run/$prog.pid
HOMER_CONFIG="-config-path /usr/local/homer-core/etc/homer.json"
DESC="HOMER Application Server"
start() {
	log_daemon_msg "Starting $DESC" "$prog"
	start_daemon -p $PIDFILE /usr/local/homer-core/bin/homer $HOMER_CONFIG
	if [ $? -ne 0 ]; then
		log_end_msg 1
		exit 1
	fi
	if [ $? -eq 0 ]; then
		log_end_msg 0
	fi
	exit 0
}

stop() {
	log_daemon_msg "Stopping $DESC" "$prog"
	killproc -p $PIDFILE /usr/local/homer-core/bin/homer
	if [ $? -ne 0 ]; then
		log_end_msg 1
		exit 1
	fi
	if [ $? -eq 0 ]; then
		log_end_msg 0
	fi
}

force_reload() {
	stop
	start

}

case "$1" in
start)
	start
	;;
stop)
	stop
	;;
force-reload)
	force_reload
	;;
restart)
	stop
	start
	;;

*)
	echo "$Usage: $prog {start|stop|force-reload|restart}"
	exit 2
	;;
esac
